### ISSUE TITLE
[Sprint 1] uri 파서 만들기

### ISSUE THREAD

**Issue by Two-Jay** [FT-369/webserv#11]
http 통신을 하기위해 uri 파서를 만들어봅시다.

**### ToDo**

- [ ] uri 가 무엇인지 파악하고 포스팅을 공유합니다.
- [ ] url 을 파싱할 수 있는 기능을 구현합니다.
- [ ] urn 을 파싱할 수 있는 기능을 구현합니다.
- [ ] 적절하게 나중에 이를 이어줄 수 있도록 클래스로 모듈화를 진행합니다.
